### ISSUE TITLE
💸 Mint: remove deprecated `x/param` from mint module

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#328]
###  📝 Purpose

The mint module use old deprecated `x/param` module to store the module parameters. As recommended by [cosmos](https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#xparams), we need to migrate all our modules param into the state of the module. PR and exemple is given for the `x/mint` module of cosmos chain: https://github.com/cosmos/cosmos-sdk/blob/v0.46.1/UPGRADING.md#xparams

This has been already done in #313 for the `x/logic` module.

### 📋 Todo

- [x] Implement store param from `x/mint` state module
- [x] Update proto with `MsgUpdateParam` transaction
- [x] Implement `MsgUpdateParam` tx 
- [x] Add migration script to migrate param from `x/param` module to `x/mint` state
- [x] Update docs

### 🧪 Tests

- [x] Param access
- [x] Migration
- [x] Governance proposal to update param
