### ISSUE TITLE
⬆️ Upgrade to cosmos-sdk 0.47.x

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#331]
### 📝 Purpose

To follow new feature and security update, we need to upgrade the `cosmos-sdk` to the new released version `v0.47.1`. 

### 📋 Todo

- [ ] Update cosmos-sdk [v0.47.1](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.47.1)
- [ ] Update Dockerfile to build and generate new proto : https://github.com/okp4/docker-images/pull/154
- [ ] Generate new protobuf file
- [ ] Migrate logic module
- [ ] Migrate mint module
- [ ] Migrate vesting module
- [ ] Create Upgrade handler for migration from 0.46.x to 0.47.x
